# Generated by Django 4.0.4 on 2022-06-06 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('gender', models.BooleanField(choices=[(0, 'male'), (1, 'female')])),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(default='no_picture.png', upload_to='patients')),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.commune')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universal', models.CharField(max_length=250, unique=True)),
                ('fdi', models.CharField(max_length=250, null=True, unique=True)),
                ('palmer', models.CharField(max_length=250, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=10000)),
                ('final_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.step')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.dentist')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='VisitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.visitstatus')),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.visit')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.step')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemDetected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.problemcatalog')),
                ('selected', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected', to='patients.treatment')),
                ('suggested', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested', to='patients.treatment')),
                ('tooth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.tooth')),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=5000)),
                ('path', models.FileField(upload_to='docs')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.visit')),
            ],
        ),
    ]
